# Generated by Django 3.2.16 on 2023-12-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='unit_of_measurement',
            new_name='measurement_unit',
        ),
    ]
