# Generated by Django 3.2.16 on 2023-12-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_unit_of_measurement_recipeingredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'грамм'), ('ml', 'миллилитр'), ('pcs', 'штука'), ('tbsp', 'столовая ложка'), ('to taste', 'по вкусу'), ('pinch', 'щепотка')], default='g', max_length=50, verbose_name='Единица измерения'),
        ),
    ]
