# Generated by Django 3.2.16 on 2023-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20231219_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(choices=[('Salt', 'Соль'), ('pepper', 'Перец'), ('sugar', 'Сахар'), ('flour', 'Мука'), ('butter', 'Масло'), ('onion', 'Лук'), ('garlic', 'Чеснок'), ('tomato', 'Помидор'), ('chicken', 'Курица'), ('beef', 'Говядина')], max_length=256, verbose_name='Ингредиент'),
        ),
    ]
