version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: postgre_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: arttmikh/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/


  frontend:
    container_name: frontend
    image: arttmikh/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static:/frontend_static

  gateway:
    container_name: nginx
    image: arttmikh/foodgram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media

    ports:
      - 8000:80