version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: postgre_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend_prod
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    container_name: frontend
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static:/frontend_static

  gateway:
    container_name: nginx
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8000:80